### ISSUE TITLE
Build MVP Network API

### ISSUE THREAD

**Issue by cadecairos** [mozilla/network-api#1]
* Python/Django
* PosgreSQL 9.6
* Admin interface for changing structured data
* GitHub login (use org teams to determine if access is granted)

related: https://github.com/mozilla/network/issues/42

**Comment by cadecairos** [comment]
@gvn @simonwex @gideonthomas

**Comment by gvn** [comment]
Related: https://github.com/mozilla/network/issues/42

**Comment by gideonthomas** [comment]
In case you don't run Zenhub, here are the big key pieces that need to be implemented:
- #2 Create the scaffolding
- #3 Add People to the django application
- #7 Create staging/production instances
- #8 Add Github authentication for the admin interface
