### ISSUE TITLE
Landing Pages and Opportunity Features

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-api#102]
Let's discuss use cases for Landing Pages and Opportunity Features. 

Today, there's a 1 to 1 relationship between these content types. That's not likely to be the case down the road. Here are some use cases to help guide how you decide to build this.

**Opportunity Feature A** – We feature an opportunity. Link to a landing page. e.g. Internet Health report. 

**Opportunity Feature B** – We feature an opportunity from a network partner. Link to a page on their site. [I'm not certain we will do this. But it seems probable the need will emerge.] 

**Landing Page A** – We build a landing page for an opportunity, featured as opoprtunity. e.g. Internet Health. 

**Landing Page B** – We build a landing page for a new advocacy thing, linked to from twitter, not featured as an opportunity. e.g. Copyright FAQ for upcoming vote. [Note: these would be simple advocacy pages, for quick turnaround. Bespoke advocacy pages with complex functionality should be infrequent, and built outside of the CMS] 

**Landing Page C** – A web fellow creates a landing page for their work. Link to from a Medium blog post, Pulse, Github. Not featured as opportunity. e.g. Intro to a research report. 

cc @gvn @gideonthomas @Pomax

**Comment by hannahkane** [comment]
@xmatthewx - can you clarify the use case for Landing Page B? What's an example of a advocacy thing that would make use of a simple page? Would these be content pieces that drive Network sign-ups?

**Comment by xmatthewx** [comment]
I think we need to clarify this as you mentioned in meeting with drivers on Wednesday. I spoke briefly with Jordan about the current project to build a page for copyright call tool. I think we all need to meet to talk about other advocacy use cases, to see what could be enabled by cms, soapbox, vs what will need to remain bespoke. 

For the purposes of this issue, it's essentially the same as Page C, but with staff vs non-staff authors.

**Comment by hannahkane** [comment]
Cool. It's on my list to set up that meeting. In the meantime, I think we can go with the use case as you've defined it.

**Comment by gvn** [comment]
Maybe I'm missing something, but aren't Landing Page B and C basically the same? An unfeatured landing page?

**Comment by xmatthewx** [comment]
B and C are similar from out team's perspective, yes. I've separated them as fairly different use cases for our stakeholders (who authors, traffic we push from Mozilla channels, expectations on quality control). We might learn something from those use cases that surface some requirements the change our thinking.

**Comment by simonwex** [comment]
We have separated out the models for pages and for features. This enables us to do all the cases above.
