### ISSUE TITLE
Actually automate network template to mezzanine network-api deploys

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-api#115]
We finished the autogeneration step in the network repo, so we'll have to figure out the automation step that kicks in on a build to copy over any new template generated to mezzanine. Ideally only when the diff says there's a difference, but it won't hurt to just blinding copy it due to its small size.

**Comment by Pomax** [comment]
repo https://github.com/pomax/filebrowser_s3

**Comment by simonwex** [comment]
From @cadecairos:
 * When we merge into master on network repo
 * Trigger staging build on jenkins
 * Add post-build step to jenkins that commits file directly to github repo

**Comment by cadecairos** [comment]
This is complete.

I've set this up like so:
1. A staging build of the network site completes, the generated template file is archived in the build's folder.
2. A new job (copy-network-templates-to-mezzanine) is set up to watch for completed builds of "Network (staging)" and begins executing.
3. It copies the archived template file from `$JENKINS_HOME/jobs/Network (staging)/builds/lastStableBuild/archive` into the workspace (which is a clean version of `network-api@master`)
4. It commits the change.
5. The master branch in the workspace is pushed to `mozilla/network-api@master`

**Comment by cadecairos** [comment]
One thing to note: The build is being marked as failed if there aren't any changes to commit... I'm investigating whether this can be worked around.

**Comment by cadecairos** [comment]
Fixed this by adding `set +e` to the top of the shell script step, so that it doesn't bail at the first non-zero exit code. 

I separated the commit from the copy, so that if the copy fails, the build will fail. It's okay if we don't have anything to commit.

**Comment by cadecairos** [comment]
marking this resolved.
