### ISSUE TITLE
make "signup" an optional block

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-api#118]
either
- non-require field (nullable)
- checkbox to include a signup at all
- ???
- profit

and:
expose a value to the template that allows setting of a class to hide a 2nd column

This may need a template update to make the signup conditional, and it might need conditional styling to go from 2-col to 1-col

**Comment by simonwex** [comment]
@gvn to file ticket in network repo for template changes

**Comment by alanmoo** [comment]
Will this need design changes since it would result in a single column page with the current design?

**Comment by alanmoo** [comment]
I realize the previous question is better for the other repo, and is completely separate work than what is required in this ticket. So, this is ready for engineering.

**Comment by Pomax** [comment]
The signup form was switched over to optional (see https://github.com/mozilla/network-api/blob/master/app/networkapi/landingpage/models.py#L36) but this issue was not closed.
