### ISSUE TITLE
see if we can rename langingpage to page in the admin view pulldown

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-api#119]
having a string "landing page" in the pulldown for what in terms of staffing is just "A page" may be confusing. We should see if we can rename that in the admin so the page pulldown says "page".

**Comment by alanmoo** [comment]
@Pomax I believe this is now solved, right?

**Comment by Pomax** [comment]
@pomax to verify

**Comment by Pomax** [comment]
confirmed, we can close this
