### ISSUE TITLE
hide some of page creation pulldown, or refine what they present

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-api#120]
We don't want every pulldown menu to show the way it does right now in the admin view (for instance, should landing pages allow further landing page children? maybe? maybe not?)

discuss O_O

**Comment by simonwex** [comment]
@cadecairos could you add some notes here?

**Comment by cadecairos** [comment]
* Dive into the mezzanine source to find & understand the page admin template
* copy the template into network-api so we can override it
* replace drop downs with a "create page" button.
