### ISSUE TITLE
add a policy/explainer text to the page create admin template

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-api#121]
Right now the template says "Select Page to change" and that's it, let's add some text that explains how to actually add a landing page to the set of page.

**Comment by simonwex** [comment]
Also answer the question, "why isn't my random page showing up at /imawesome/"

**Comment by alanmoo** [comment]
#137 will change the Select box to a link that says "Add page". I think that addresses the first part of this issue. @simonwex, what are you thinking for your comment? A little piece of text that says "pages exist at https://network.mofoprod.net/opportunity/{slug}"?

**Comment by simonwex** [comment]
I think explaining the routing like you suggest above, @alanmoo is what we need. It's still very easy to create a page that never gets routed to and it's not obvious to the user why.

**Comment by Pomax** [comment]
Are we trying to solve for "what is the url for my page?" (which is an education issue, given the "view on the site" button top right) or "the url for my page doesn't work" because they forgot to manually set a slug? (which would be something we can fix in code)

**Comment by alanmoo** [comment]
I think we just want something like this, no?
<img width="723" alt="image" src="https://cloud.githubusercontent.com/assets/1682681/25713434/a5350292-30c2-11e7-9eb4-e63834363706.png">

**Comment by Pomax** [comment]
Note that a "slug" is an animal, though; not a web page.

However, what is the problem we're solving? This solution feels like it solves a dev problem ("where do slugs point?") rather than a user problem ("I want to get to my page on the URL I expected it to be")

**Comment by alanmoo** [comment]
This issue has been technically solved, let's continue the conversation about sub-headers on admin pages in #148
