### ISSUE TITLE
brand our mezzanine

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-api#123]
currently the admin panel says mezzanine, this should be moz://a

![screenshot 169](https://cloud.githubusercontent.com/assets/177243/24931628/cf9ee51e-1ec2-11e7-9510-71fa78921664.png)

**Comment by simonwex** [comment]
This is the file that needs changing:
https://github.com/stephenmcd/grappelli-safe/blob/master/grappelli_safe/templates/admin/includes_grappelli/header.html

You can see discussion here: https://groups.google.com/forum/#!topic/mezzanine-users/NVbGiPT6eHg

**Comment by alanmoo** [comment]
Unless I'm missing something, it looks like this is now hard-coded into the template.

https://github.com/stephenmcd/grappelli-safe/blob/master/grappelli_safe/templates/admin/includes_grappelli/header.html#L6

**Comment by Pomax** [comment]
worst case, we do a full template file copy to overload it, but it's probably worth filing a PR that fixes this in mezzanine. And then we do a full file copy until that lands >_>

**Comment by Pomax** [comment]
I've asked this question over on https://groups.google.com/forum/#!topic/mezzanine-users/Y-iAoQTLwxs
