### ISSUE TITLE
update filebrowser_s3 to a "final" version that we can walk away from because it works

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-api#126]
update https://github.com/mozilla/network-api/pull/125 with 0.1.0 and remove the now unused var

**Comment by Pomax** [comment]
AWS_STORAGE_ROOT is messing us up something fierce

**Comment by Pomax** [comment]
This has been fixed, filebrowser_s3 is now on v0.1.18 and if we want we can term this v1.0.0

work for you @cadecairos?

**Comment by cadecairos** [comment]
Yup, go for it

**Comment by Pomax** [comment]
v1.0.0 published
