### ISSUE TITLE
Possibly remove "featured" flag in page model.

### ISSUE THREAD

**Issue by simonwex** [mozilla/network-api#127]
I think the featured checkbox is no longer valid now that we have a feature model.

True/false, @Pomax?

![image](https://cloud.githubusercontent.com/assets/25260/25098731/8adaa558-235e-11e7-89dc-e7dfa47d75de.png)

**Comment by Pomax** [comment]
no idea - if someone knows how to explain landing page vs. opportunity vs feature, let me know. I have *no* idea what this checkbox is for =)

@gvn would you happen to know?

**Comment by gvn** [comment]
Featured controls whether it shows up on the homepage or not.

**Comment by alanmoo** [comment]
Closing, as we need to leave that flag.
