### ISSUE TITLE
Add network 404 page to network-api

### ISSUE THREAD

**Issue by simonwex** [mozilla/network-api#128]
Replace this:

![image](https://cloud.githubusercontent.com/assets/25260/25099557/af67ef5e-2361-11e7-89bb-c176ee75f731.png)

With whatever is created here: mozilla/network/issues/143

It should also be copied over using the same process as #115

**Comment by simonwex** [comment]
Blocked on mozilla/network#143

**Comment by arush0311** [comment]
It should be solved now.

**Comment by alanmoo** [comment]
404's all seem to go to the same page spot now.
