### ISSUE TITLE
Update Django to 1.11.0 (LTS)

### ISSUE THREAD

**Issue by cadecairos** [mozilla/network-api#130]
https://www.djangoproject.com/weblog/2017/apr/04/django-111-released/

Lets upgrade Django to 1.11.0, which is an LTS release and will recieve update untill December 2017.

**Comment by cadecairos** [comment]
cc @gideonthomas @Pomax @simonwex

**Comment by gideonthomas** [comment]
sounds good! There doesn't seem to be any changes that would break stuff we wrote but don't know about what would break with Mezzanine.

**Comment by cadecairos** [comment]
Blocked on https://github.com/stephenmcd/mezzanine/issues/1749

**Comment by alanmoo** [comment]
Issue moved to [mozilla/network #650](https://github.com/mozilla/network/issues/650) via [**ZenHub**](https://www.zenhub.com/)
