### ISSUE TITLE
Update news item model

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-api#133]
News items need a few new properties:

`isVideo` boolean
`thumbnail` image, optional

Does this sound right @xmatthewx? I bet the logic could get more complicated but this feels like the easiest way to get what we want.

Once done, please comment on https://github.com/mozilla/network/issues/328

**Comment by gvn** [comment]
Recommend `isVideo` instead of just `video`.

**Comment by xmatthewx** [comment]
👍 

Fine to gather thumbnails on all items. Could use them down the line. No need to build in that logic.

**Comment by alanmoo** [comment]
Closed by #183
