### ISSUE TITLE
Landing Page model needs to be deployed to production

### ISSUE THREAD

**Issue by simonwex** [mozilla/network-api#134]
It shows the old model structure:
![image](https://cloud.githubusercontent.com/assets/25260/25284080/c7e056a0-266a-11e7-8b89-c38d0ae8e1dd.png)

**Comment by cadecairos** [comment]
Deployed to production - found issue with s3 media library not working on production. Should we file another issue?

**Comment by simonwex** [comment]
yar

**Comment by cadecairos** [comment]
Closing this out then, and opening an issue to track production s3 filebrowser issues.
