### ISSUE TITLE
Pull back HTML cleaning for pages

### ISSUE THREAD

**Issue by simonwex** [mozilla/network-api#135]
Enable embedding of Youtube videos

**Comment by alanmoo** [comment]
I'm not quite sure what the subject of this issue means; something about embedding HTML in page content?

**Comment by alanmoo** [comment]
Let's try to enable embedding through the editor before resorting to disabling sanitation.

**Comment by simonwex** [comment]
Allowing youtube embeds would solve this issue.

**Comment by Pomax** [comment]
This might be a matter of going into the admin "site settings" and changing the tinymce setting from "high security" to "medium"

**Comment by alanmoo** [comment]
@cadecairos to investigate if flipping the switch solves the issue

**Comment by cadecairos** [comment]
I've set the Rich Text Filter to "low" which enables staff to input <video> <iframe> and <object><--- (plz, don't) tags using the source editor widget button. 

![firefox_2017-05-04_16-34-08](https://cloud.githubusercontent.com/assets/438003/25723823/9e909030-30e7-11e7-989f-2233f6c5d0ac.png)
