### ISSUE TITLE
Make sidebar less confusing

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-api#139]
Duplicate items on the sidebar are confusing.
<img width="212" alt="image" src="https://cloud.githubusercontent.com/assets/1682681/25341144/e4d9780a-28d5-11e7-8cde-a82b4766d7da.png">
Can we eliminate duplicates? Is this happening because each blue heading is an app? What's the point of the white sub-headings under them?

**Comment by alanmoo** [comment]
@cadecairos @Pomax @gvn @kristinashu Thoughts?

**Comment by kristinashu** [comment]
Yes, definitely seems overfill to repeat the titles. How customization is this? 

For reference, here's the CMS benchmark deck Megan made https://docs.google.com/presentation/d/1wIFku0mq7OKj_BhpXJJV0q4z5lPn5YfsiulhxpzS7XA/edit?usp=sharing

**Comment by Pomax** [comment]
To explain what we're looking at, the big blue titles are "app names", and the white links are specific types of data that an app has a model for. Mezzanine itself, for instance, has the `Content` app with the two top level models `page` and `Media Library`, but so far in the network-api we're using separate apps with single models per app, so you see the app name, and the model name, and in almost all cases those are the same. They represent different things, though.

**Comment by alanmoo** [comment]
Based on the call, we have a few options:

1. Template shenanigans
2. Rename things
3. Consolidate some models into their own apps

Anything else I'm missing?

1 feels like a hack to me, going with 2 feels like addressing the symptoms and not the issue. That leaves 3, which seems to be somewhere in a gray area re: organization. I could make an argument that all these things are models within a "Network data" application, but can also see the inverse logic.
