### ISSUE TITLE
Make accessing the admin easier

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-api#140]
https://network-api.mofoprod.net/admin/ isn't exactly an easy url.

At the very least, can we make https://network-api.mofoprod.net/ go to the admin login, since we're not using the homepage?

Ideally I'd think `{finalURL}/admin`  would be best, but am open to ideas.

(Yes, bookmarks are a thing but why not make it memorable as well?)

Thoughts @cadecairos?

**Comment by cadecairos** [comment]
`https://network.mofoprod.net/admin` is already implemented and working.
