### ISSUE TITLE
Adding a "feature" isn't working.

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-api#144]
https://network-api.mofostaging.net/admin/features/feature/add/

Filling in that page results in an error on submission.

Related: #145

**Comment by Pomax** [comment]
Can we add an explanation of what these are in this issue?

**Comment by alanmoo** [comment]
The "features" are a type of meta tag for pages that are being linked to from the "Get Involved" section of the homepage. This is the same spot that "featured" opportunity pages would appear, but for urls that are not on the network site itself.

**Comment by Pomax** [comment]
This looks like it's related to image uploads, which we need to fix through filebrowser_S3

**Comment by Pomax** [comment]
fixed by fixing the filebrowser_s3 problems.
