### ISSUE TITLE
add smoke testing for Staging

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-api#152]
We've broken `network` twice now by things going wrong in `network-api` prod pushes. It's time to add some security measures there so that a stage push can flag errors that should clearly prevent us from prod pushing.

**Comment by alanmoo** [comment]
Right now we don't have an environment in which the client site uses a staging api. Perhaps we should spin up another test box for a smoke test, at the very least?

**Comment by cadecairos** [comment]
I can set this up

**Comment by cadecairos** [comment]
okay, I've set up the following:

1. network-smoketest S3 bucket
2. [Network (Dev)](https://jenkins.mofoprod.net/job/Network%20(dev)/) Jenkins job
3. CloudFront distribution: EI0ZQ4OL54LF9 (mofo-projects)
4. A record and AAAA record aliased to d321xfqpumqu4u.cloudfront.net

However, the JSON endpoints are hard coded in [fetch-json.js](https://github.com/mozilla/network/blob/f0a8ed89295a320dc862948d1f511d9061cdcf18/scripts/fetch-json.js#L21-L27) and will need to be set up for configuration. Ideally via using `process.env`, with a fallback to what it currently is.

**Comment by cadecairos** [comment]
Created https://github.com/mozilla/network/pull/350 to address the domain problem.

**Comment by Pomax** [comment]
all the work that can be done in this repo has been done, domain problem to be handler in the network repo.
