### ISSUE TITLE
Implement Google Authentication

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-api#153]
First round of improved authentication, aimed at staff since they all have an account already.

**Comment by Pomax** [comment]
This will be tackled in two parts:
- [ ] implement a custom user class that acts as a pass through model that has all the hooks to start extending, but does not change how login works out of the box
- [ ] add a separate route for gauth login that gets exposed on the admin login template such that users see "either log in with your username and password or click here to log in via gAuth"
  - [ ] copy over the gauth logic from network-pulse-api
  - [ ] override the admin template

**Comment by Pomax** [comment]
Actually, instead I figured I'd give python social auth another go, given that it's now a new ecosystem of libraries (core + framework specific) and that worked brilliantly.

The only thing that's not done as part of this ticket is setting permissions automatically based on whether a user is in some org or not. That feels... reasonable? We can bulk-set permission through groups instead.

**Comment by Pomax** [comment]
![image](https://cloud.githubusercontent.com/assets/177243/25501908/4c3b4062-2b49-11e7-8e3e-7a574a83000c.png)
