### ISSUE TITLE
media browser: you can upload a file "too early"

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-api#160]
This will fail:

1. media browser
2. click upload
3. browse for image
4. click upload when you've selected an image

This will succeed:

1. media browser
2. click upload
3. browse for image
4. wait for your filename to show on the page after selecting an image
5. click upload

**Comment by alanmoo** [comment]
A js file somewhere should probably disable the "upload" button until the browser has finished ingesting the file.

**Comment by arush0311** [comment]
Can i take this?

**Comment by alanmoo** [comment]
Go for it

**Comment by arush0311** [comment]
@pomax doesn't filename showup instantaneously after selecting a file?

**Comment by Pomax** [comment]
@arush0311 unfortunately not: if you pick a properly large image, like a 10MB file from a digital camera, then it can take a few seconds before the filename shows up.

**Comment by arush0311** [comment]
Hmm. I had to extend the `FILEBROWSER_MAX_UPLOAD_SIZE` to upload more than 5 MB files and then too the image name appers instantaneously..

**Comment by Pomax** [comment]
Are you running this with S3 enabled?

**Comment by arush0311** [comment]
no. but that shoudn't be a problem right? because we are talking before the upload.
