### ISSUE TITLE
Improve testing by use of mock/copy-of-production data

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-api#162]
Related to #152, now that we've got some real data we should be able to populate both staging and dev environments with a snapshot of that data, or perhaps regular snapshots in the case of staging?

What's the best approach for this?

@cadecairos @Pomax @gvn

**Comment by cadecairos** [comment]
Well, we could get clever and write a django management command (`python manage.py copydata $DESTINATION_DB_URL`) that grabs the data and copies it over to staging. Then we can just trigger the command regularly using the heroku scheduler addon.

The command would need to take care of the following:

1. copy all objects in: pages, news, people, features, +other associated models
2. update image links - since staging uses a different S3 bucket. This could be changing something to a default, or downloading the image and re-uploading the result to the staging bucket.

**Comment by arush0311** [comment]
Woudn't copy of production data potentially expose sensitive info?

**Comment by Pomax** [comment]
staging does not do anything more, or less, than production, so simply duplicating the data such that both environments have the same data backing does not expose anything that isn't already exposed.

**Comment by arush0311** [comment]
what about potential bugs? it would be less profound in staging than review apps but it would still exist.

**Comment by Pomax** [comment]
Bugs in what? This issue about back-syncing data from production to staging, so that *staging* can run with true data, and reveal bugs before code is promoted to production (with every successful promotion to production being a signal for a back-sync)

**Comment by arush0311** [comment]
Hm, say there is a bug in my patch that reveals sensitive information. From https://devcenter.heroku.com/articles/github-integration-review-apps#the-postdeploy-script see warning below

**Comment by Pomax** [comment]
as long as we empty the user table from real users, there is no "sensitive information" that can be exposed.

**Comment by arush0311** [comment]
perhaps we could use heroku database fork in staging but it wont be possible in review apps.

**Comment by Pomax** [comment]
https://devcenter.heroku.com/articles/github-integration-review-apps#the-postdeploy-script suggests we have enough control to make it possible for review apps.

**Comment by arush0311** [comment]
hmm can we run heroku commands in post deploy? we will have to check

**Comment by Pomax** [comment]
Presumably that is what they had in mind when they introduced https://devcenter.heroku.com/articles/github-integration-review-apps#heroku_app_name-and-heroku_parent_app_name -- while the names might change, they're probably still going to be useful.

**Comment by alanmoo** [comment]
Issue moved to [mozilla/network #651](https://github.com/mozilla/network/issues/651) via [**ZenHub**](https://www.zenhub.com/)
