### ISSUE TITLE
Long term goals of indicating featured content

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-api#163]
I'm not entirely sure our current model of identifying featured content will scale, or at least if users will understand how to make the things they want happen. Some of our content types have a "featured" flag right now, but it's not clear what that does or where the content will appear. And since this can be different types of content (people, news, links), there aren't currently consistent fields that exist which would allow a single endpoint of different types of featured items.

From the other perspective, if a user wants to make something show up on the homepage, how can we make that clear? In the near term the plan seems to be simply grabbing the top "featured" items from a data type, but that approach doesn't feel like it's going to work long term.

Thoughts? @gvn @xmatthewx @Pomax

**Comment by xmatthewx** [comment]
tracking in #507
