### ISSUE TITLE
Straighten out "features" model

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-api#164]
I just spoke to @xmatthewx about the "features" model and the inconsistency of it is a bit confusing, especially as our needs have evolved. Currently, that model simply maps to the "Get Involved" section of the homepage.

There are three ways I see forward:

1.) Expose the landing pages as an api route and add/modify some fields on them so that they have the appropriate data to pull into the homepage, based on the existing "featured" checkbox. (Ideally those extra fields would only show up when "featured" is checked, and only to a subset of users)

2.) Drop the "featured" checkbox from opportunity pages and effectively use "Features" as a list of items to appear on the homepage. We should probably rename it to something like "featured homepage links" or "get involved links".

3.) Agree that "Get Involved" items are all things that could be in Pulse, and as such simply create a model for them that lets us select 3 pulse projects to highlight. I'm mainly throwing this in here as another way to think about the data model, though I think it has shortcomings too.

1 is a little more work for developers one time, 2 is more work for editors every time. I also like 1 because it's then consistent with the news and people sections as they exist today.

Thoughts @gvn @simonwex @xmatthewx @cadecairos @Pomax?

**Comment by alanmoo** [comment]
Based on the conversation in our call today:

* We'll call these things "highlights"
* We can feature highlights on the homepage. This should be done by a view that allows you to change settings on the homepage and select the highlights you want on the homepage. (We'll probably extend this view in the future to support other homepage customizations)
* Model for highlights:
    * Title
    * Image (required?)
    * Description (string)
    * Link
    * Link text (CTA)

The one thing this doesn't account for is the "See More Projects" button that's currently below the Pulse entry on the homepage. Is that part of the data or part of the template for now?

After thinking about it more, I'm still a little unsure about these being structured content (description as a string, forcing the link below it). Is there any reason for it to be an HTML field instead? Or do we start with the above and see if it needs to evolve into HTML later, because that's easier than the reverse?

cc @taisdesouzalessa @sabrinang

**Comment by gvn** [comment]
I think we should leave it as structured data, but consider allowing HTML in the description.

**Comment by xmatthewx** [comment]
I _think_ we can close this based on #507. To unblock work in #203. Plz reopen if I'm mistaken.
