### ISSUE TITLE
Add new field to people model

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-api#168]
On the people model we need a link field, verbose name "Interview Link".

See https://github.com/mozilla/network/issues/359

**Comment by gvn** [comment]
Suggest we add to the existing `link` array, like so:

```
      "links": {
        "type": "object",
        "properties": {
          "twitter": {
            "type": "string"
          },
          "linkedIn": {
            "type": "string"
          },
          "interview": {
            "type": "string"
          }
        }
      },
```

**Comment by alanmoo** [comment]
return in API as `links.interview`
https://github.com/mozilla/network/pull/374/commits/6cc057b27c9642db828240a953edb8c293cda3e0
