### ISSUE TITLE
Indicate people are "featured" on sort view

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-api#188]
If users of the back-end know which people cards are featured, it should make it easier to drag and drop in an order that doesn't break the site layout.

**Comment by alanmoo** [comment]
A stretch goal of this would be to set the width of profiles based on their "featured" state, so that unfeatured people could be 50% wide and simulate the layout on the front-end.

**Comment by Pomax** [comment]
initial pass idea: use flex box, set "priority" to "put this first in the list" so that featured entries show up top, and colour them a little differently/add a `::before` content that puts a little "featured" box on top of each?

**Comment by alanmoo** [comment]
Not sure that achieves what we're trying to do; Primarily we want to see which people are featured within the current ordering method. It's important that they stay in that order, so admins know what to expect on the public site.
