### ISSUE TITLE
Make "log in with Google" more prominent

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-api#191]
Since it's the main way people will log in, let's hide the regular login behind some JS so the Google link is most prominent.

**Comment by alanmoo** [comment]
@xmatthewx Can we get a quick design pass on this?

https://network.mofostaging.net/admin

**Comment by xmatthewx** [comment]
Like this? 

<img width="731" alt="screen shot 2017-05-11 at 7 29 43 pm" src="https://cloud.githubusercontent.com/assets/53411/25976045/3a7fc284-3680-11e7-9757-8b744653d095.png">

@sabrinang @taisdesouzalessa – can one of you make this a bit better? Nothing crazy, just a box, better hierarchy. Quick and simple.

**Comment by taisdesouzalessa** [comment]
@xmatthewx I am not sure what is the ask here. Are we hiding the fields and just leaving the copy? Fields are just available once users click on one of the options?

For login with Google or a username/password approach this is usually the model I see on the sites - this example is from Pocket:

<img width="371" alt="image" src="https://cloud.githubusercontent.com/assets/22157921/25976277/bbce79a6-3668-11e7-94a9-714ceef38b9f.png">

**Comment by xmatthewx** [comment]
We want to encourage log in with google and hide email/password behind the link. This gives us less risk because then we don't manage personal information. (Alan will correct me if I'm wrong). 

So the task for you or Sabrina is to treat my mockup as a wireframe and add a bit of UI love. Simple is fine. The top gray bar with site title will remain unchanged right now.

Let's wait for @alanmoo to reply.

**Comment by alanmoo** [comment]
Google login is the only option, except for dev/administrators. So the button and an "admin login" link below that shows the full login box is probably just fine.

**Comment by xmatthewx** [comment]
Ah, good to know. 

So @taisdesouzalessa, instead of "More options" we should have an "Admin" link. It should be lowest in visual hierarchy, below forgot password.

**Comment by alanmoo** [comment]
Forgot password is tied to the admin login form, since Google handles forgotten passwords too

**Comment by xmatthewx** [comment]
Another aha. Trying again: 

So... we want Login with Google button with a small admin link below. I think we should stick with our UI style instead of introducing something google-like. Forgot password link will be hidden with the email/password form.

**Comment by sabrinang** [comment]
@xmatthewx Here is a simple iteration (very similar to what exists which I think is the request):
<img width="1329" alt="simple login" src="https://cloud.githubusercontent.com/assets/2492510/26008587/43bd79fc-36fa-11e7-869d-dbaddca8ad23.png">

I wasn't to sure what the field "Interface: •Admin ◦Site" does but this could be simplified to reduce confusion though.

**Comment by xmatthewx** [comment]
thumbs up!

**Comment by Pomax** [comment]
admin vs site basically decides where to send you after authentication, so clicking "admin" will take you into the admin panel, clicking site logs you in but then sends you on to the main site (so you see the site but with anything that's locked behind a login now visible to you, like user-only downloads, forum, etc, etc. we don't do anything special there though so for us there's no real value in the "site" link)

**Comment by xmatthewx** [comment]
if `Interface: Admin || Site` can be hidden, feel free.
