### ISSUE TITLE
group all pulse-api models under a single nav header

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-api#196]
We want a single header ("Pulse API" or something) which houses:
- creators
- entries 
- tags
- issues
- (pulse) userprofiles

**Comment by alanmoo** [comment]
I'm not seeing anything on network-dev currently, is that expected?

**Comment by Pomax** [comment]
Your account's now a superuser: you should see pulse entries, issues, etc. in the admin interface with your mofo login now

**Comment by alanmoo** [comment]
Got it. So something similar to the work done in https://github.com/mozilla/network-api/commit/3248efc5c534dadb180cc4a7b4b8de13a6ebfb9b

**Comment by Pomax** [comment]
yeah - thanks for the commit link, that's good to have in the issue for reference!

**Comment by alanmoo** [comment]
Closing this for now as we're not merging pulse in at the moment.
