### ISSUE TITLE
[ADMIN] Add ability to upload images

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-api#20]
### Details

Allow administrators to upload images for resources that need an image in their models. For e.g., each People model needs a photo of the person. Admins should be able to upload this via the admin interface.

### Implementation

Use S3 to back this. Use https://github.com/boto/boto3 to allow uploading to s3. Have an `image_url` to store the resulting url.

**Comment by simonwex** [comment]
Check in with @Pomax as he's doing image upload for pulse.

**Comment by Pomax** [comment]
this was how we were going to do it. Have the user upload a BLOB, have the server send that blob to S3, get a URL back, and then store that URL in the data model (this also allows the user or an admin to set a URL rather than a blob if they already have a suitable image online)

**Comment by simonwex** [comment]
Is there any reason we wouldn't use an already-made solution like this?
https://github.com/bradleyg/django-s3direct

**Comment by Pomax** [comment]
I can't speak for this project, but I couldn't find a way for that to also allow for passing "either data or a URL", it *has* to be files, so for the network pulse API that seemed needlessly restrictive.

**Comment by simonwex** [comment]
Restrictive, why? I don't understand the need for the blob. 

It's super rare that S3 goes down and I'm find pegging our uptime to it. Cloudfront would have held up the consuming side.

**Comment by Pomax** [comment]
I'm not sure I understand what you mean with "need for the blob"? For the network pulse api we wanted to be able for users to either send an entry "thumbnail" image, or a thumbnail url if there is already a suitable image associated with the entry. No blobs are involved other than when the user is sending an image file along with their entry, for django to save on S3.

**Comment by simonwex** [comment]
Having the image hosted on our kit seems like a good idea to avoid broken images on services we don't control, anyway. Let's take the easy path here.

**Comment by Pomax** [comment]
There might be a misunderstanding here: both boto and s3direct send the data to S3, we don't keep the image on our own server, we only send it on during the post, and then only record the resultant S3 URL in both cases.

**Comment by Pomax** [comment]
just noticed this closed - doesn't the PR used make django save all the images locally?

**Comment by cadecairos** [comment]
You can let it use local saving for dev, but enable s3/cloudfront on staging/production, via ENV var

**Comment by Pomax** [comment]
ah, cool
