### ISSUE TITLE
Pulse migration

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-api#200]
We should figure out an approach for migrating the Pulse db into network-api.

**Comment by Pomax** [comment]
the tricky bits:
- pulseapi:users has to get split up into a socialauth:user and a pulseapi:userprofile
- pulse users will need to be assigned a sensible default user group

as we're migrating the pulseapi into a "blank" networkapi as far as pulse data goes, we should be okay wrt the other things (issues, tags, entries, moderation states, etc)

**Comment by Pomax** [comment]
We have decided not to go through with this for now. We can refine when the pulse API codebase is closer to a standard Django form.
