### ISSUE TITLE
Whoops – CMS pages

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-api#207]
I jumped on CMS to create a new page to test a thing. 

I clicked "Opportunity" in the screenshot below, thinking it would expand the list. And then thought, hmmm, that's odd that it triggered a new draft page. I thought the content there was placeholder on a new item, and then proceeded to edit the page and wonder why I couldn't see it. I have a terrible cold and should be in bed. And, others could be confused too. 

<img width="660" alt="screen shot 2017-05-17 at 4 24 54 pm" src="https://cloud.githubusercontent.com/assets/53411/26174469/7d0f3ec6-3b1d-11e7-9fc7-0a92eeedf902.png">

I'm guessing this a real page, though one we redirect to the homepage. True?

Could an edit of this page break paths on subpages? Can we add some more verbose help text in the content fields?

cc @alanmoo

**Comment by alanmoo** [comment]
Only if you change the meta-data route does it possibly break the other routes. But I agree, this should be...not able to happen. My original plan was to auto-expand the list (#192), but perhaps we also disable the link on the top level page so people can't accidentally go in and edit it?

**Comment by xmatthewx** [comment]
Definitely. If we can disable or hide it. And we could change title to Opportunities (plural) so it feels more like parent to a list. 

I'd call this fairly critical before we more authors beyond Kevin, Jesse, Claw.

**Comment by alanmoo** [comment]
Are you saying the routes should be `/opportunities/*`?

**Comment by xmatthewx** [comment]
Just the label. Since it's visually like a header to the list. That was my foggy-headed assumption, that it was a header and not that it was a parent page. Again, foggy headed, but good as test for other users.

**Comment by alanmoo** [comment]
I changed the label in the CMS. Closing this in favor of the actual ask in #208
