### ISSUE TITLE
Return news date in standard format

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-api#210]
The `YYYY-MM-DD` format is causing warnings in MomentJS. (https://github.com/mozilla/network/issues/380#issuecomment-302514898)

**Comment by Pomax** [comment]
What is "standard format"? UTC datetime using full ISO format?

**Comment by alanmoo** [comment]
"RFC2822 or ISO format", though I'm realizing that may not be the necessary solution here- we may just need to tell Moment what the format is when we import from the API. Commenting in original ticket

**Comment by arush0311** [comment]
Is this still valid?

**Comment by Pomax** [comment]
I'm not sure. @gvn @alanmoo was this fixed entirely in the network repo, or is further work necessary here?

**Comment by gvn** [comment]
I worked around it on the front end, so it's not crucial, but it would be nice to standardize.

`¯\_(ツ)_/¯`

**Comment by alanmoo** [comment]
@arush0311 It looks like this came from news articles often only having a publish date, not a time too. Can you investigate what the ISO standards that MomentJS uses say about dates without times? That will help us figure out what approach to take here.

**Comment by arush0311** [comment]
Turns out this is not about server not returning dates in ISO formats but a hardcoded news object whose date format was not in standard format. https://github.com/mozilla/network/blob/98d2e091106980bbcc8bbfbe5a4e0cf0e41164d7/source/pug/views/home.pug#L78. this hardcoded news object is no longer present

**Comment by alanmoo** [comment]
Awesome! Thanks for digging that up.
