### ISSUE TITLE
Update readme to explain env variables behavior in docker

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-api#213]
Changing the env variable isn't working properly for local development, it's always trying to access the production server for assets. I'm not sure if this is a code bug or a documentation issue.

-----
Ask after conversation: Update Readme to document Docker's behavior

**Comment by alanmoo** [comment]
I suspect this might not have been working for a while, but only recently manifested due to CSP implementation.

**Comment by cadecairos** [comment]
When you change the environment variable, do you bring down the docker stack and rebuild it with `docker-compose up --build`?

**Comment by gvn** [comment]
I just tried that and I'm still seeing the default `network.mofoprod.net` getting set in the landing page template when it's sent to the client.

EG:

in: `app/networkapi/templates/pages/landingpage.html`

`<link rel="stylesheet" href="https://{% settings_value "ASSET_DOMAIN" %}/_css/main.compiled.css">`

is being output as:

`<link rel="stylesheet" href="https://network.mofoprod.net/_css/main.compiled.css">`

when I set my `.env` to:

`ASSET_DOMAIN=localhost:5000`

**Comment by alanmoo** [comment]
It does seem to work on the server, https://network-dev.mofostaging.net/opportunity/internet-health-report/ has the appropriate resource links, which is why I wonder if it's a documentation issue of sorts.

**Comment by gvn** [comment]
It seems like a local dev issue if anything. Maybe something with Docker not consuming `.env`?

**Comment by cadecairos** [comment]
docker doesn't read `.env` - it's crappy, but you have to make changes to the default env file...

**Comment by gvn** [comment]
Ah. That sucks, but it explains the issue. We should add this to the README.

**Comment by Pomax** [comment]
nah, we should fix that instead. @cadecairos what is involved with making docker read an .env file instead?

**Comment by cadecairos** [comment]
As far as I know, `docker-compose` can only read in a single environment file (`env.default`) when building the container. we'll need to have Django read in settings from another file outside of source control and override the environment variables in the container.

**Comment by Pomax** [comment]
Reading through https://docs.docker.com/compose/env-file/ and https://docs.docker.com/compose/environment-variables/#the-env-file it sounds like docker needs `.env` "for itself", with secondary file(s) for actual runtime variables.

Can we rename the defaults.env to `network-api.env` and then document the fact that env vars that django/mezzanine rely on should go in that file?

**Comment by alanmoo** [comment]
Is there a way to ensure changes to that env file don't get committed/pushed back up?

**Comment by gvn** [comment]
It's a tad hacky maybe, but we could commit defaults and then write a script that merges overrides into defaults and emits a file that Docker ultimately consumes.

**Comment by Pomax** [comment]
https://stackoverflow.com/questions/18276951/how-do-i-stop-git-from-tracking-any-changes-to-a-file-from-this-commit-forward sounds like a lockdown command that we can automate as an npm post install action, so that default.env can be changed without it ever being pushed back up, but then of course it'll be a little bit of work to update when we do need to change it (with new vars for instance)

**Comment by Pomax** [comment]
I've updated hte README.md with https://github.com/mozilla/network-api/blob/master/README.md#pre-setup-a-note-about-env-files which documents the current situation, and will file a new issue to investigate actually making docker load env. vars from a private environment file that is not under revision control.
