### ISSUE TITLE
Enable 404 page

### ISSUE THREAD

**Issue by gvn** [mozilla/network-api#214]
We will soon have a 404 page available when https://github.com/mozilla/network/issues/411 lands, but we'll need it wired up.

I believe this just means redirecting 404s to `/errors/404`.

**Comment by gvn** [comment]
This is ready for a redirect now. @cadecairos can you add that?

**Comment by arush0311** [comment]
Can I take this?

**Comment by Pomax** [comment]
@arush0311 you bet!

**Comment by Pomax** [comment]
Reopening this issue, as https://network-dev.mofostaging.net/ejnfoinweoifw does not show the 404 page getting served. It's possible @cadecairos needs to work some additional magic at the cloudfront level.

**Comment by arush0311** [comment]
Just for information, the mezzanine subpaths will redirect to `/errors/404` only when debug is set to true.

**Comment by Pomax** [comment]
Note that we still need to make sure that the `errors/404` route returns a 404. @cadecairos is this a thing we need to set over on S3?

**Comment by cadecairos** [comment]
I just modified the cloudfront distribution for staging with what I believe will display `/error/404` for all 404 response codes from any of the origins in the distribution. Let's test in 20-30 minutes.

**Comment by Pomax** [comment]
interesting. Right now the mezzanine instance effects the 404 by doing a 302 to /errors/404.html... would that mean our code would bypass the possible solution you just put in place because it doesn't generate a real 404 code?

**Comment by arush0311** [comment]
I think so :P

**Comment by cadecairos** [comment]
> would that mean our code would bypass the possible solution you just put in place because it doesn't generate a real 404 code?

Yes, if django short-circuits the default behaviour of sending a 404, Cloudfront will take no action.

This isn't terrible, but we could safely remove it and let Cloudfront handle serving the right content on 404s. I can see this being troublesome if Cloudfront or browsers start caching 302s if we make a mistake, and fix it.

In other news, I've implemented the 404 behaviour on all three network site CDNs (dev, staging, production)

**Comment by Pomax** [comment]
We can "blank" the 302 redirect and see what this now does on admin routes. @arush0311 would you be willing to form a PR to bypass the 404 redirect again?

**Comment by arush0311** [comment]
sure!

**Comment by Pomax** [comment]
I think that's probably easiest, yes. Or we can keep the code and hide it behind an `if False:` rather than `if DEBUG is False:`

**Comment by Pomax** [comment]
looks like the cloudfront solution @cadecairos put in place works great, so I will close this issue
