### ISSUE TITLE
cannot read env variables

### ISSUE THREAD

**Issue by arush0311** [mozilla/network-api#229]
the following code in settings.py does not read `.env` file at the right location. 
```
# Read in the environment
if os.path.exists('.env') is True:
    environ.Env.read_env('.env')
else:
environ.Env.read_env()
```
I suggest using three levels of project structure instead of just two (`root`, `app`)
`app` seems to be a misnomer as it refers to `app/networkapi`. How about `repo`, `root` and `app`.

**Comment by Pomax** [comment]
Remember to run `python app/manage.py ...`, do not run `python manage.py` inside of the app directory
