### ISSUE TITLE
Audit the code for queryset caching

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-api#232]
From #219 we learned that queryset objects are cached for as long as Django can, and so in order to ensure that we always work with the most recent view of the database, we had to rewrite the `People` list view queryset into a def. changing:

```
queryset = People.objects.public()
```
to:
```
def get_queryset(self):
    return People.objects.public()
```
This fixes things for `People` data in the database, but we need to audit the rest of our code to see if we might have this problem anywhere else that we've simply not run into yet, but is just waiting to trip us up.

**Comment by arush0311** [comment]
So, we also use queryset attribute in APIViews of `highlight` and `news` app, this will lead to caching of these database records and the updated records may not be accessed. So the files that need to be changed are:

- [*] app/networkapi/highlights/views.py
- [*] app/networkapi/news/views.py

**Comment by Pomax** [comment]
nice, thanks for looking into this!
