### ISSUE TITLE
document a code comment tag that indicates modifications

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-api#236]
I'd like to suggest we formally document that we should be using `override: start` as a code comment prefix and `override: end` as code comment suffix around blocks of code we modify.

Additional, we should also have code comments following any `override: start` that explain the modification, and point to the github URL for the issue that is the primary driver for introducing that change to the codebase.

**Comment by Pomax** [comment]
This will require updating several files that we already made modifications to in the `app/networkapi/static` as well as the `app/networkapi/templates` directories

**Comment by arush0311** [comment]
> Additional, we should also have code comments following any override: start that explain the modification

@pomax In my case the overridden content was several blocks of lines in different places, all collectively doing the same thing. What about override: start <keyword> and we explain those keywords at top of file? Also I think we should also comment out the removed content instead of deleting them

**Comment by Pomax** [comment]
I'd suggest `override: start #12345` in that case (with corresponding `end`) where `12345` is an issue number. That way custom code can always be traced back to the "why" at the project level.

**Comment by Pomax** [comment]
added to the redme

**Comment by alanmoo** [comment]
@gvn something for MoFo standards maybe?

**Comment by gvn** [comment]
Yeah that seems reasonable, although fairly domain specific if it's just regarding Mezzanine?

**Comment by Pomax** [comment]
I guess the idea is mezzanine here, but for any framework that we use where we need to "monkey patch" (I know that's not what this is, technically, but taking a 2000 line file and updating 10 lines sure feels like it =D) it's good to know there's one particular style we use, modulo the actual comment syntax (`<!-- -->` vs `# ... ` vs `''' ... '''` vs `/* ... */` vs `{# ... #}` vs etc. etc.)
