### ISSUE TITLE
Change default permissions for Mozillians

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-api#242]
As part of the RRA, it was recommended that we don't automatically allow anyone from Mozilla to add pages or change data.

@xmatthewx I believe we initially did this intentionally, but does it make sense to add staff permissions by person now? We can still make use of groups for easy permission assignment.

**Comment by xmatthewx** [comment]
That's fine. We can give access as needed.

**Comment by Pomax** [comment]
This will require updating the code in https://github.com/mozilla/network-api/blob/master/app/networkapi/utility/userpermissions.py

**Comment by alanmoo** [comment]
<img width="872" alt="screen shot 2017-07-13 at 8 05 33 pm" src="https://user-images.githubusercontent.com/1682681/28192839-c33da796-6806-11e7-932d-50e540480d6a.png"> from https://network.mofoprod.net/admin/auth/group/1/change/

I think if we change some of those to less...empowering(?) defaults we'll be good. That way we still have staff marked as staff and can adjust in the future as necessary.

**Comment by alanmoo** [comment]
On second thought, if we just remove the items from the right column we should be good.

**Comment by Pomax** [comment]
Suggested course of action:
- remove automatically adding users to any groups based on email address
- do a manual pass to see which users that are currently assigned the `staff` group should get unassigned
- keep the staff policies broad, but manually assign permissions from now on for new users who we know need them.

**Comment by Pomax** [comment]
also:
- add a test to verify that a new moz user is not automatically staff

**Comment by Pomax** [comment]
closing for now, filed https://github.com/mozilla/network-api/issues/259 for followup
