### ISSUE TITLE
Changing order of highlights doesn't work

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-api#244]
STR:

1. Visit https://network.mofoprod.net/admin/highlights/highlight/
2. Click "change order" button at top right

Expected behavior:

The same type of "change order" screen that "People" has should appear.

**Comment by alanmoo** [comment]
My first instinct is that this may be due to images being not required, but the template for the change order page expects them.

**Comment by arush0311** [comment]
I am taking this issue! :raised_back_of_hand:

**Comment by alanmoo** [comment]
It would appear that #245 took care of this- at least on staging, ordering works if a highlight doesn't have an image.

**Comment by alanmoo** [comment]
This was indeed fixed by #245
