### ISSUE TITLE
Add logging for templating errors

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-api#246]
We've been bitten by template errors silently breaking things when `DEBUG=False`, we need to find a way to enable logging of template errors so that when things break, they at least do not break silently.

**Comment by arush0311** [comment]
Can i take this?

**Comment by alanmoo** [comment]
Issue moved to [mozilla/network #652](https://github.com/mozilla/network/issues/652) via [**ZenHub**](https://www.zenhub.com/)
