### ISSUE TITLE
Build "Upcoming" items model

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-api#247]
@alanmoo commented on [Tue Jul 18 2017](https://github.com/mozilla/network/issues/575)

This could be an extension or rename of the "Highlights" model, but we need to have the conversation in #574 first.

The schema will presumably look like https://github.com/mozilla/network/blob/master/source/json/upcoming.schema.json so that implementation on the front end is straightforward.

**Comment by alanmoo** [comment]
As decided in https://github.com/mozilla/network/issues/574#issuecomment-316266364, this should be a new model.

**Comment by alanmoo** [comment]
I'm going to rename this "Events" since they're Upcoming Events, and it's hard to work one's head around a model that's not a noun. Any objections? @xmatthewx?

**Comment by xmatthewx** [comment]
I'm not opposed. Upcoming would include something like the upcoming release of the health report. Less event like than MozFest. I also fear requests for an events calendar. I'm not opposed, just wary.

**Comment by alanmoo** [comment]
Understandable. Is there a better word? Because "upcomings" that are in the past make no sense whatsoever.

**Comment by xmatthewx** [comment]
> "upcomings" that are in the past make no sense whatsoever.

😆 maybe to you, but not to the prophets living in the wormhole. 

Moments? Milestones? Opportunities? ~~Highlights?~~ We can use Events if we're stuck. Just leave a comment to beware of dragons.

**Comment by alanmoo** [comment]
Lets go with Milestones

**Comment by xmatthewx** [comment]
Should we bump this to the current heartbeat @alanmoo - or is it done and ready for review? If so, how do I review?

**Comment by alanmoo** [comment]
https://network-dev.mofostaging.net/admin/milestones/milestone/

**Comment by xmatthewx** [comment]
Looks great in Mezzanine. Thanks. Do we have a corresponding ticket to migrate existing content and connect with frontend?

**Comment by alanmoo** [comment]
https://app.zenhub.com/workspace/o/mozilla/network/issues/624
