### ISSUE TITLE
Remove user-associated profiles when deleting a user

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-api#250]
right now deleting a user can lead to an error:
```
IntegrityError at /admin/auth/user/
Exception Value: update or delete on table "auth_user" violates foreign key constraint "userprofile_userprofile_user_id_59dda034_fk_auth_user_id" on table "userprofile_userprofile"
DETAIL:  Key (id)=(......) is still referenced from table "userprofile_userprofile".
```
so we need to update the user model(s) such that when a user gets deleted, the associated user profile gets removed as well.

**Comment by alanmoo** [comment]
Issue moved to [mozilla/network #648](https://github.com/mozilla/network/issues/648) via [**ZenHub**](https://www.zenhub.com/)
