### ISSUE TITLE
add an indicator to the user admin to show which account is django vs. social auth

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-api#251]
social auth users cannot be deleted except through the social auth => users panel, so it will be good to highlight which user is of which type in the users => user panel

**Comment by arush0311** [comment]
can i take this?

**Comment by alanmoo** [comment]
Issue moved to [mozilla/network #653](https://github.com/mozilla/network/issues/653) via [**ZenHub**](https://www.zenhub.com/)
