### ISSUE TITLE
see if we can rename the `is_staff` flag to `has_admin_access` to reflect what it does

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-api#252]
right now the user model has an `is_staff` flag that does *not* tell us whether someone is a mozilla staffer, but tells Django that the user has rights to open the `/admin` link, without saying anything about what they can then do in the admin interface.

We should probably try to rename that to `has_admin_access` or the like.

**Comment by alanmoo** [comment]
Issue moved to [mozilla/network #649](https://github.com/mozilla/network/issues/649) via [**ZenHub**](https://www.zenhub.com/)
