### ISSUE TITLE
problems getting admin access for new users

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-api#254]
We changed the perms/group policies for new users, turning off special rights for moz accounts, but that might have had an effect on new users - A user is reporting that they tried an initial log in to the admin site, and now even though their user account has `is_staff` set and their user has been assigned to the `staff` group, the admin page keeps saying that they do not have permission to view the admin interface.

marking this as bug for further investigation.

**Comment by arush0311** [comment]
Is this about setting site for users? I had a similar problem but setting site for a user fixed that.

**Comment by Pomax** [comment]
excellent point, morphing this issue into an implementation issue to restore automatically adding the user to the site, without restoring automatic permission/group assignments.
