### ISSUE TITLE
Cannot upload thumnails in local dev

### ISSUE THREAD

**Issue by arush0311** [mozilla/network-api#256]
uploading a thumbnail in news admin gives me a server error.. I tracked it down to https://github.com/mozilla/network-api/blob/master/app/networkapi/utility/images.py. @alanmoo  Is this the case with production too?

For some reason `prop_name` passed to `get_image_upload_path` is `headline` in case of `glyph` but `thumbnail` in case of `thumbnail`.

@Pomax  django documentation mentions only two arguments `instance` and `filename` to `upload_to` of `Filefield`. Where are other arguments coming from?

**Comment by alanmoo** [comment]
Looks like the same thing happens in production.

It doesn't sound like the problem, but FYI: I recall some logic being built in to gracefully handle image uploading when on a local environment (without an AWS API key). I doubt that's what's getting in the way, but might be some useful background to be aware of.

**Comment by arush0311** [comment]
Here is the problem. https://github.com/mozilla/network-api/blob/master/app/networkapi/news/models.py#L20
since we are passing thumbnail as prop_name and thumbnail is filefield, we cannot slug it..

**Comment by alanmoo** [comment]
Great, wanna open a PR?
