### ISSUE TITLE
refine the user groups

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-api#259]
right now we have admin and staff, and a defunct pulse-related group. We should probably extend that a bit into
- staff (no special permissions?)
- admin (all perms)
- editor (editing rights on all objects)
  - [xyz] editor (editing rights on specific objects)

**Comment by arush0311** [comment]
Do we have to create a migration or do that manually?

**Comment by alanmoo** [comment]
Issue moved to [mozilla/network #646](https://github.com/mozilla/network/issues/646) via [**ZenHub**](https://www.zenhub.com/)
