### ISSUE TITLE
Decide on Auth system

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-api#28]
We're trying to decide on what auth strategy to use for the network-api and for our CMS work in general. It would be good to consolidate our Auth strategy across our CMS implementations.

Our current thought is to use Github authentication here.

**Rationale for Using Github**
- Allows us to manage permissions for existing staff using the Github Mozilla org's teams to assign who has access to what
- Allows us to easily add contributors and assign permissions based on the org teams

Network Pulse uses Google Auth instead. We would like to understand the rationale behind choosing that for the pulse api as well as understanding the pros/cons of using google auth vs. github auth vs. something else.

**Comment by simonwex** [comment]
@xmatthewx @Pomax @mmmavis it's key to use the same strategy moving forward across our content editing tools. Do you have any thoughts? It's my understanding that it would be technically simple to swap google for github in our current implementation.

**Comment by Pomax** [comment]
Is there a good reason for not going with "all common social logins" so we get github for free because those already cover google, github, facebook, twitter, etc.?

**Comment by xmatthewx** [comment]
My preference would be for google or all common social logins. Is there a user case for Github? Short-term, google is easy since all staff have it. MId-term, we aim to have non-staff users who do not work with software (a policy fellow, a thought leader), who post to Pulse and potentially craft simple landing pages for an initiative.

**Comment by simonwex** [comment]
The win for using Github is solely that we manage our contributor's access there currently–we use Github for content other than code. If we're commonly going to have users that do not have a Github account, I'd also vote for Google. 

I'd vote against the "Nascar login" (all social providers) as users forget which service they use for what.

**Comment by Pomax** [comment]
nothing wrong with opinionated nascar: "Click here to log in with github" and a text link "or click here to see more login options". I've seen a fair few sites do this, and it works as a nice funnel.

**Comment by xmatthewx** [comment]
> Nothing wrong with opinionated nascar

I'm down with an aspiration for an opinionated nascar. 

> If we're commonly going to have users that do not have a Github account, I'd also vote for Google.

I vote we start with Google and ask Kristina to gather a few benchmarks for "View more login options". I recommend we keep design investment light until we have secondary options in development.

**Comment by gideonthomas** [comment]
@simonwex, what's the verdict on this?

**Comment by gideonthomas** [comment]
@simonwex re-pinging about this. Does this need to be a part of MVP?

**Comment by simonwex** [comment]
For MVP let's use built-in auth flow. There aren't so many that it'll be a serious task to input them manually.

I've filed this: https://github.com/mozilla/network-api/issues/92
