### ISSUE TITLE
Define staff workflow for adding content

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network-api#48]
Apologies if this has been discussed elsewhere.

We need to determine how staff members will trigger an update to the production site based on changes to the CMS. Ideally they have a way to preview their changes on a staging server, and they can update the site without engineer involvement.

**Comment by alanmoo** [comment]
@cadecairos will #131 address this?

**Comment by cadecairos** [comment]
Yes it will

**Comment by alanmoo** [comment]
To keep this separate from the technical discussion over there, what's the workflow going to look like? (Updates on production API show up on staging? How do they get to production front end?)

**Comment by cadecairos** [comment]
> Updates on production API show up on staging

yes, the idea here is that someone can edit a person/news/feature entry, and trigger an automatic staging build after {undetermined_number} seconds[1] without an additional edit to a model.

1. my proposed debounce timeout is 5 minutes, with a 15 minute cooldown (max 3 staging deploys per hour - but this is completely configurable via ENV so we can play around with it easily.

> How do they get to production front end?

TBD - but options include a slack integration (for specific people only), or perhaps a special button on the admin available only to folks in a specific permissions group.

**Comment by alanmoo** [comment]
This will be documented in #143, with the "deploy to production from staging" being accomplished at the moment by "bug someone in Slack"
