### ISSUE TITLE
Formatting on bio field in People module

### ISSUE THREAD

**Issue by hannahkane** [mozilla/network-api#49]
I can't see the bio field being displayed right now, so I can't confirm this, but I'm assuming the bullet points I'm adding (using markdown) aren't going to render.

I'm not sure if we'll solve this on the back end in Django, on the front end, or simply by requiring that the content in this field not include bullets.

**Comment by cadecairos** [comment]
@hannahkane we determined that the bio field would just be a single text field on the back-end, without any kind of markdown formatting.

@gvn @alanmoo Have we given thought to how this will work on the front end?

**Comment by gvn** [comment]
Is there any reason we couldn't store markdown in that field?

**Comment by gideonthomas** [comment]
We can store markdown. It's just bad UX though since you're entering markdown in a textarea essentially.

**Comment by hannahkane** [comment]
It might not be the best longterm solution, but I think I'd prefer it at this point, if the alternative is rewriting all the bios so that they make sense without bullet points.

**Comment by gideonthomas** [comment]
@hannahkane so, you can add markdown in the text currently. The front-end would just need to add code to interpret that.

**Comment by hannahkane** [comment]
Thanks, @gideonthomas. Closing this here. Commented in relevant front-end issue.
