### ISSUE TITLE
refine the "eventual flow" diagram 

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-api#58]
There is a picture on my desktop, it needs to be a lucid chart.

**Comment by Pomax** [comment]
view-only link: https://www.lucidchart.com/invitations/accept/2d681c61-d13a-4f62-af5d-800113819f09

(let me know if you need edit rights and aren't @wex or @gideonthomas)

**Comment by gideonthomas** [comment]
Moving out of this current milestone since we still need to settle on what the "eventual flow" will look like

**Comment by simonwex** [comment]
Diagram updated and included in README.md
