### ISSUE TITLE
[PEOPLE] Add model

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-api#6]
Create model and migration

**Comment by simonwex** [comment]
Schema here:
https://github.com/mozilla/network/blob/master/source/json/people.schema.json

Dummy data here:
https://github.com/mozilla/network/blob/master/source/json/people.json

**Comment by gideonthomas** [comment]
Fixed with 3c96c0d83ebbce38093fe7b5222e86a3f848d086
