### ISSUE TITLE
Validate user flow for creating a LandingPage for FeaturedOpportunities that includes an inline image

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-api#61]
* Walk Kevin through this process, gather feedback
 * Generate issues for training and follow-on heartbeat

**Comment by Pomax** [comment]
Try to implement https://projects.invisionapp.com/share/ZJ9YTAGEA#/screens/216715361

**Comment by Pomax** [comment]
blocked on https://github.com/mozilla/network-api/pull/105

**Comment by cadecairos** [comment]
This is no longer blocked - landing pages are live on staging: https://network.mofostaging.net/admin

**Comment by cadecairos** [comment]
This is no longer blocked - landing pages are live on staging: https://network.mofostaging.net/admin

**Comment by Pomax** [comment]
## usertesting notes

- what is the "label" for?
- puzzling on where an uploaded image went on first pass
  - clicked image instead of selector link
  - found the selector link almost immediately after
- adding a second image went without any issues
- signup dropdown: edited an existing CTA rather than making a new signup
- when explained that signups could be shared amongst pages used the + to make a new page-specific CTA 

## liked
- and a high level: pleasantly surprised with the experience
- incredibly straight forward CMS
- rich text is really easy, images are great
- having control over headers and signup are bonus features
- didn't see gaps or holes in the creation/edit flow, meets all the needs
- editing is "super easy"


## disliked
- "very minor hiccup on how to include my image on the page but I figured it out in seconds"

## unexpected
- media browser lag did not seem a problem on staging, and did not illicit any comments during use, nor any upon review. So maybe our S3 solution isn't as slow as we think it is?

## delightful
- we got congratulations on making something this good

**Comment by cadecairos** [comment]
> what is the "label" for?

I honestly have no idea. @gvn? (`label` field on the landing pages content type)


> puzzling on where an uploaded image went on first pass

everyone (including myself) seems to trip over this - but recovers quickly once they find the right button.



> media browser lag did not seem a problem on staging, and did not illicit any comments during use, nor any upon review. So maybe our S3 solution isn't as slow as we think it is?

\o/

**Comment by gvn** [comment]
`label` is the copy associated with the link to the page from the homepage feature group.

<img width="392" alt="screen shot 2017-04-11 at 2 08 25 pm" src="https://cloud.githubusercontent.com/assets/206379/24930986/5f9da996-1ec0-11e7-8734-00f968ca217b.png">

EG: "Be a fellow" and "Be a leader" are `label`s.

**Comment by Pomax** [comment]
hm, are these actually used in landing pages?

**Comment by gvn** [comment]
Not on the page itself, but it's basically metadata that is needed.

**Comment by Pomax** [comment]
isn't it only needed when there is a block that uses it, though? (e.g. similar to the signup block, where the data is defined only when used?)

**Comment by Pomax** [comment]
closing this as "we did this and filed issues based on the feedback"
