### ISSUE TITLE
Revise Opportunities model and enable in editor

### ISSUE THREAD

**Issue by gvn** [mozilla/network-api#78]
New Schema: https://github.com/gvn/network/blob/db418862efaaf14c8c57c3b751350e8d2e241582/source/json/opportunities.schema.json

Note that `content` and `sign-up.description` expect HTML and will need TinyMCE enabled in the admin interface.

`slug` can be generated from the `name` attribute.

**Comment by gideonthomas** [comment]
Will need to investigate how mezzanine will send the structured json for opportunities for the homepage. For the actual page, we will rely on Mezzanine to generate the unstructured page and host it.

**Comment by simonwex** [comment]
To Close, ensure we have an accurate features model ticket.
