### ISSUE TITLE
Create "LandingPage" Model

### ISSUE THREAD

**Issue by cadecairos** [mozilla/network-api#82]
* Title
 * Content (rich text)
 * Publish & Expiry dates
 * SignupCTAHeader
 * SignupCTASubheader (rich text)

#### Functionality

 * Slug should be generated by title with "opportunity/" prefixed
 * 

Example:
https://network.mofostaging.net/opportunity/fellowships/

**Comment by Pomax** [comment]
most of this has been done in https://github.com/mozilla/coss/tree/mezzanine/network already

**Comment by cadecairos** [comment]
fixed in #105
