### ISSUE TITLE
set up a hook to send built templates over to mezzanine

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-api#89]
there's a few places this could be done, any post-build moment should work for this purpose. We basically need to do a push into the mezzanine repo for known files.

For testing, this should probably go into its own dir, so we can do manual verification, with the mezzanine settings updated to be aware of this new template location.

**Comment by simonwex** [comment]
@cadecairos had discussed setting up template-loading in mezzanine to possibly load from S3. This feels lower priority than the other things in this milestone. If it needs pushing out, I think that's fine.

**Comment by Pomax** [comment]
tracking on the `network` repo
