### ISSUE TITLE
[PEOPLE] Add data

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-api#9]
Add data from existing json file into staging/production databases: https://github.com/mozilla/network/blob/master/source/json/people.json

**Comment by gideonthomas** [comment]
Not migrating that file ^.

@gvn will link to the actual data

**Comment by gvn** [comment]
https://docs.google.com/spreadsheets/d/1rwNFjojmnOHkctAIAin9Pd_rxziscGJBSWi-z2S6Bg4/edit#gid=866621792
