### ISSUE TITLE
Design CloudFront distribution

### ISSUE THREAD

**Issue by simonwex** [mozilla/network-api#95]
We need to set cloudfront up so that we can support the public routes (Opportunities) from Mezzanine and the rest from the S3 bucket. Eventually, we'll add more routes to the Mezzanine origin.

**Comment by simonwex** [comment]
We should make sure we don't cache requests made by admins.

**Comment by cadecairos** [comment]
I've modified the CloudFront distribution we're using for network.mofoprod.net - here's what I've done:

1. I've added the `network-api.mofoprod.net` origin to the distribution
2. I added a behaviour - `/opportunities/*` that will forward requests matching that regex to the new origin -  this will serve up [landing pages](https://github.com/mozilla/network-api/pull/105) we publish on the mezzanine app.
3. I added a behaviour - `/admin/*` which will forward requests matching that regex to the new origin - this will serve up the admin interface. I configured it to forward the `sessionid` and `csrftoken` cookies, and the `Host` header to the new origin. It's configured to pass GET, HEAD, OPTIONS, POST, PUT, and DELETE requests.

**Comment by cadecairos** [comment]
I was able to successfully implement this on staging!

I can't enable it on production yet because a fix for configuring allowed hosts for csrf token validation is blocked from reaching production by the missing sorting that's on staging.

This will be addressed in #99

**Comment by cadecairos** [comment]
This has been implemented on staging and production.

The django app can now be accessed through `/admin`, and `/opportunities/<slug>` will be proxied to django.
